spring:
  profiles:
    active:
      - db
  datasource:
    url:
      jdbc:mysql://localhost:3306/metricdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui
      operations-sorter: method